import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>QuoteMe | Make your day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <small className={styles.description} style={{marginBottom: '6rem'}}>
      <a href="\" style={{fontWeight: 700, color: '#0070f3'}}>QuoteMe</a> 😊
      </small>

        <h1 className={styles.title}>
          Welcome to <span style={{color: '#0070f3'}}>QuoteMe</span>
        </h1>

        <div className={styles.grid}>
          <a onClick={QuotMe} className={styles.card}>
            <h2 style={{marginBottom: 0}}>Click me to get a quote &rarr;</h2>
          </a>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Jishnu-Dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by{' '}
          <span style={{fontWeight: 800, color: '#0070f3'}} className={styles.logo}>
            Jishnu Raj
          </span>
        </a>
      </footer>
    </div>
  )
}

function QuotMe() {
  return (
  fetch('https://api.quotable.io/random')
  .then(response => response.json())
  .then(data => {
    var quote = data.content
    // var author = data.author
    alert(quote)
    console.log(`${data.content} —${data.author}`)
  })
  )
}
