import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
// import Image from 'next/image'

export default function Home() {
  let brand = 'QuoteMe'
  let [quote, setQuote] = useState(null)
  let [author, setAuthor] = useState(null)

  async function randomQuote() {
    const response = await fetch('https://api.quotable.io/random')
    const data = await response.json()
    setQuote(data.content)
    setAuthor(data.author)
    // console.log(`${data.content} —${data.author}`)
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>QuoteMe | Make your day</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

      <small className={styles.description} style={{marginBottom: '6rem'}}>
      <a href="\" style={{fontWeight: 700, color: '#a8a8a8 '}}>QuoteMe</a> 😊
      </small>
        
        <h1 className={styles.title}>
          {quote ? quote:`Welcome to ${brand}`}
        </h1>
        <h3 style={{color: '#0070f3'}}>{ author ? `- ${author}`:null }</h3>

          <a onClick={randomQuote} className={styles.card}>
            <h2 style={{marginBottom: 0}}>Read &rarr;</h2>
          </a>

        <div className={styles.grid}>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/Jishnu-Dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made by{' '}
          <span style={{fontWeight: 800, color: '#0070f3'}} className={styles.logo}>
            Jishnu Raj
          </span>
        </a>
      </footer>
    </div>
  )
}